Update documentation
eiffel-community/eiffel-remrem-generate pull request #187
Opened 2021-12-03 10:42 UTC by shubhamkumarguptaTCS

### Applicable Issues

Syntax errors in curl command in documentation for remrem generate.

### Description of the Change

Updated the remrem generate curl commands documentation with correct syntax.

### Alternate Designs

### Benefits

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: <!-- SHUBHAM KUMAR GUPTA shubhamkumar.gupta1@tcs.com

2022-01-17 11:59 UTC, iamrishavkumar requested changes

2022-01-17 11:59 UTC, iamrishavkumar commented on CHANGELOG.md
> +- Updated the REMRem Generate all curl commands in documentation
Rephrase this sentence

2022-03-22 06:02 UTC, dhruvin-kalavadia approved these changes

2022-03-22 06:56 UTC, Vaishnavi-Enugala approved these changes

2022-04-29 10:11 UTC, merged