Update generate endpoint for gen1 template
eiffel-community/eiffel-remrem-generate pull request #231
Opened 2024-10-29 08:22 UTC by shudhansu-shekhar

### Applicable Issues

### Description of the Change

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: <shudhansu shekhar> <shudhansu.shekhar.ext@ericsson.com>

2024-10-29 12:01 UTC, z-sztrom requested changes

2024-10-29 12:01 UTC, z-sztrom commented on service/src/main/java/com/ericsson/eiffel/remrem/generate/controller/RemremGenerateController.java
> +//            JsonObject eventResponse = new JsonObject();
remove unused code

2024-10-29 12:01 UTC, z-sztrom commented on service/src/main/java/com/ericsson/eiffel/remrem/generate/controller/RemremGenerateController.java
> +           /* JsonObject eventResponse = new JsonObject();
remove unused code

2024-10-29 13:08 UTC, shudhansu-shekhar commented on service/src/main/java/com/ericsson/eiffel/remrem/generate/controller/RemremGenerateController.java
> +                      /*  partialSuccess = true;
Done

2024-10-29 13:11 UTC, shudhansu-shekhar commented on service/src/main/java/com/ericsson/eiffel/remrem/generate/controller/RemremGenerateController.java
> +//            JsonObject eventResponse = new JsonObject();
Done

2024-10-29 13:12 UTC, shudhansu-shekhar commented on service/src/main/java/com/ericsson/eiffel/remrem/generate/controller/RemremGenerateController.java
> +           /* JsonObject eventResponse = new JsonObject();
Done

2024-10-29 13:53 UTC, shudhansu-shekhar reviewed
Remove the unused code, please look

2024-10-30 11:35 UTC, z-sztrom approved these changes

2024-10-30 11:38 UTC, merged